extends Note

@export var tile_interval := 1.0

func _ready() -> void:
	note_path = [
		# Note head
		{"tile": Vector2i(-2,8), "sprite": fill_tile_atlas_coord},
		{"tile": Vector2i(-1,8), "sprite": fill_tile_atlas_coord},
		{"tile": Vector2i(0,8), "sprite": fill_tile_atlas_coord},
		{"tile": Vector2i(1,8), "sprite": fill_tile_atlas_coord},
		{"tile": Vector2i(2,8), "sprite": fill_tile_atlas_coord},
		{"tile": Vector2i(3,8), "sprite": fill_tile_atlas_coord},
		{"tile": Vector2i(4,7), "sprite": fill_tile_atlas_coord},
		{"tile": Vector2i(3,7), "sprite": fill_tile_atlas_coord},
		{"tile": Vector2i(2,7), "sprite": fill_tile_atlas_coord},
		{"tile": Vector2i(1,7), "sprite": fill_tile_atlas_coord},
		{"tile": Vector2i(0,7), "sprite": fill_tile_atlas_coord},
		{"tile": Vector2i(-1,7), "sprite": fill_tile_atlas_coord},
		{"tile": Vector2i(-2,7), "sprite": fill_tile_atlas_coord},
		{"tile": Vector2i(-3,7), "sprite": fill_tile_atlas_coord},
		{"tile": Vector2i(-4,6), "sprite": fill_tile_atlas_coord},
		{"tile": Vector2i(0,6), "sprite": fill_tile_atlas_coord},
		{"tile": Vector2i(1,6), "sprite": fill_tile_atlas_coord},
		{"tile": Vector2i(2,6), "sprite": fill_tile_atlas_coord},
		{"tile": Vector2i(3,6), "sprite": fill_tile_atlas_coord},
		{"tile": Vector2i(4,6), "sprite": fill_tile_atlas_coord},
		{"tile": Vector2i(5,6), "sprite": fill_tile_atlas_coord},
		{"tile": Vector2i(5,5), "sprite": fill_tile_atlas_coord},
		{"tile": Vector2i(4,5), "sprite": fill_tile_atlas_coord},
		{"tile": Vector2i(3,5), "sprite": fill_tile_atlas_coord},
		{"tile": Vector2i(2,5), "sprite": fill_tile_atlas_coord},
		{"tile": Vector2i(-4,5), "sprite": fill_tile_atlas_coord},
		{"tile": Vector2i(-4,4), "sprite": fill_tile_atlas_coord},
		{"tile": Vector2i(-3,4), "sprite": fill_tile_atlas_coord},
		{"tile": Vector2i(4,4), "sprite": fill_tile_atlas_coord},
		{"tile": Vector2i(5,4), "sprite": fill_tile_atlas_coord},
		{"tile": Vector2i(5,3), "sprite": fill_tile_atlas_coord},
		{"tile": Vector2i(-2,3), "sprite": fill_tile_atlas_coord},
		{"tile": Vector2i(-3,3), "sprite": fill_tile_atlas_coord},
		{"tile": Vector2i(-4,3), "sprite": fill_tile_atlas_coord},
		{"tile": Vector2i(-4,2), "sprite": fill_tile_atlas_coord},
		{"tile": Vector2i(-3,2), "sprite": fill_tile_atlas_coord},
		{"tile": Vector2i(-2,2), "sprite": fill_tile_atlas_coord},
		{"tile": Vector2i(-1,2), "sprite": fill_tile_atlas_coord},
		{"tile": Vector2i(0,2), "sprite": fill_tile_atlas_coord},
		{"tile": Vector2i(5,2), "sprite": fill_tile_atlas_coord},
		{"tile": Vector2i(5,1), "sprite": fill_tile_atlas_coord},
		{"tile": Vector2i(4,1), "sprite": fill_tile_atlas_coord},
		{"tile": Vector2i(3,1), "sprite": fill_tile_atlas_coord},
		{"tile": Vector2i(2,1), "sprite": fill_tile_atlas_coord},
		{"tile": Vector2i(1,1), "sprite": fill_tile_atlas_coord},
		{"tile": Vector2i(0,1), "sprite": fill_tile_atlas_coord},
		{"tile": Vector2i(-1,1), "sprite": fill_tile_atlas_coord},
		{"tile": Vector2i(-2,1), "sprite": fill_tile_atlas_coord},
		{"tile": Vector2i(-3,1), "sprite": fill_tile_atlas_coord},
		{"tile": Vector2i(-4,1), "sprite": fill_tile_atlas_coord},
		{"tile": Vector2i(-3,0), "sprite": fill_tile_atlas_coord},
		{"tile": Vector2i(-2,0), "sprite": fill_tile_atlas_coord},
		{"tile": Vector2i(-1,0), "sprite": fill_tile_atlas_coord},
		{"tile": Vector2i(0,0), "sprite": fill_tile_atlas_coord},
		{"tile": Vector2i(1,0), "sprite": fill_tile_atlas_coord},
		{"tile": Vector2i(2,0), "sprite": fill_tile_atlas_coord},
		{"tile": Vector2i(3,0), "sprite": fill_tile_atlas_coord},
		{"tile": Vector2i(4,0), "sprite": fill_tile_atlas_coord},
		{"tile": Vector2i(5,0), "sprite": fill_tile_atlas_coord},
		{"tile": Vector2i(5,-1), "sprite": fill_tile_atlas_coord},
		{"tile": Vector2i(4,-1), "sprite": fill_tile_atlas_coord},
		{"tile": Vector2i(3,-1), "sprite": fill_tile_atlas_coord},
		{"tile": Vector2i(2,-1), "sprite": fill_tile_atlas_coord},
		{"tile": Vector2i(1,-1), "sprite": fill_tile_atlas_coord},
		{"tile": Vector2i(0,-1), "sprite": fill_tile_atlas_coord},
		{"tile": Vector2i(-1,-1), "sprite": fill_tile_atlas_coord},
		{"tile": Vector2i(-2,-1), "sprite": fill_tile_atlas_coord},
		# Note stem
		{"tile": Vector2i(5,-2), "sprite": fill_tile_atlas_coord},
		{"tile": Vector2i(5,-3), "sprite": fill_tile_atlas_coord},
		{"tile": Vector2i(5,-4), "sprite": fill_tile_atlas_coord},
		{"tile": Vector2i(5,-5), "sprite": fill_tile_atlas_coord},
		{"tile": Vector2i(5,-6), "sprite": fill_tile_atlas_coord},
		{"tile": Vector2i(5,-7), "sprite": fill_tile_atlas_coord},
		{"tile": Vector2i(5,-8), "sprite": fill_tile_atlas_coord},
		{"tile": Vector2i(5,-9), "sprite": fill_tile_atlas_coord},
		{"tile": Vector2i(5,-10), "sprite": fill_tile_atlas_coord},
		{"tile": Vector2i(5,-11), "sprite": fill_tile_atlas_coord},
		{"tile": Vector2i(5,-12), "sprite": fill_tile_atlas_coord},
		{"tile": Vector2i(5,-13), "sprite": fill_tile_atlas_coord},
		{"tile": Vector2i(5,-14), "sprite": fill_tile_atlas_coord},
		{"tile": Vector2i(5,-15), "sprite": fill_tile_atlas_coord},
		{"tile": Vector2i(5,-16), "sprite": fill_tile_atlas_coord},
		{"tile": Vector2i(5,-17), "sprite": fill_tile_atlas_coord},
		{"tile": Vector2i(5,-18), "sprite": fill_tile_atlas_coord},
		{"tile": Vector2i(5,-19), "sprite": fill_tile_atlas_coord},
		{"tile": Vector2i(5,-20), "sprite": fill_tile_atlas_coord},
		{"tile": Vector2i(5,-21), "sprite": fill_tile_atlas_coord},
		{"tile": Vector2i(5,-22), "sprite": fill_tile_atlas_coord},
		{"tile": Vector2i(5,-23), "sprite": fill_tile_atlas_coord},
	]
	timer.wait_time = tile_interval
	total_tiles = note_path.size()
